--- #YAML:1.0
name:                Music-Tag-MusicBrainz
version:             0.31
abstract:            Plugin module for Music::Tag to get information from MusicBrainz database.
license:             perl
author:              
    - Edward Allen (ealleniii _at_ cpan _dot_ org)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Music::Tag:                    0.27
    WebService::MusicBrainz:       0.07
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
